name: Trigger auto deployment for capp-test-oidcqwertyasdf

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/capp-test-oidcqwertyasdf-AutoDeployTrigger-26b9fd05-e294-4e78-ad9b-cbaf733c3243.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAPPTESTOIDCQWERTYASDF_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAPPTESTOIDCQWERTYASDF_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAPPTESTOIDCQWERTYASDF_AZURE_SUBSCRIPTION_ID }}

      - name: Clone azure-cli-extensions repo
        uses: actions/checkout@v3
        with:
          repository: snehapar9/test
          path: azure-cli-extensions
          
      - name: Install latest azure-cli-extensions wheel
        run: az extension add --source '${{ github.workspace }}/azure-cli-extensions/containerapp-0.3.43-py2.py3-none-any.whl' --yes

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@f2333697f3e746a4d1254ba3c1d5b20f046aff07
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CAPPTESTOIDCQWERTYASDF_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAPPTESTOIDCQWERTYASDF_REGISTRY_PASSWORD }}
          containerAppName: capp-test-oidcqwertyasdf
          resourceGroup: ca-snehapar-oidc-test-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          


